spring.application.name=demowithswiggy

# --- Local-ku badhila Live Railway DB URL ---
spring.datasource.url=jdbc:mysql://root:jRxvqfKifDkVvmvntoCELzEFZURPXceF@zephyr.proxy.rlwy.net:36831/railway?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=jRxvqfKifDkVvmvntoCELzEFZURPXceF
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

# --- Production Deployment-ku nalla dialect ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect









#Local MySQL details:
#spring.application.name=demowithswiggy

#spring.datasource.url=jdbc:mysql://localhost:3306/swiggyfoodapp
#spring.datasource.username=root
#spring.datasource.password=54321
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.main.allow-bean-definition-overriding=true
